language: node_js
node_js:
 - "8"
install:
  - npm install
notifications:
  email: false
jobs:
  include:
    - stage: build
      script: npm run lint
    - script: npm run build button
    - stage: deploy
      script: echo deploy 